# This is a basic workflow that is manually triggered

name: Create Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Version'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      changes:
        description: 'Changes in version'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4       # checkout source code
    - uses: ilammy/msvc-dev-cmd@v1    # setup developer command prompt
    - uses: laytan/setup-odin@v2.7.0
      with:
        build-type: release
        branch: master
        release: dev-2024-12
    
    # Runs a single command using the runners shell
    - name: download GNU make
      run: choco install make

    - name: build app
      run: make release

    - name: publish binary for release
      uses: actions/upload-artifact@v4
      with:
        name: torta.exe
        path: torta.exe

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: laytan/setup-odin@v2.7.0
      with:
        build-type: release
        branch: master
        release: dev-2024-12

    - name: build app
      run: make release

    - name: publish binary for release
      uses: actions/upload-artifact@v4
      with:
        name: torta
        path: torta

  create-release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest

    steps:
    - name: Download release binaries
      uses: actions/download-artifact@v4

    - name: release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.tag }}
        files: |
          torta.exe
          torta
  
