name: Test PR

# Controls when the action will run. Workflow runs when a PR is created for master
on:
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4       # checkout source code
      with:
        submodules: true
    - uses: ilammy/msvc-dev-cmd@v1    # setup developer command prompt
    - uses: laytan/setup-odin@v2.7.0
      with:
        build-type: release
        branch: master
        release: dev-2024-12
    
    # Runs a single command using the runners shell
    - name: download GNU make
      run: choco install make

    - name: test app
      run: make test
      
    - name: build app
      run: make release

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: laytan/setup-odin@v2.7.0
      with:
        build-type: release
        branch: master
        release: dev-2024-12

    - name: Install SDL2
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev libfreetype6-dev libsdl2-ttf-dev libsdl2-ttf-2.0-0

    - name: test app
      run: make test
      
    - name: build app
      run: make release
